import { links, tool, widget } from "./shape";

export const domesticChapters = [
  tool({
    slug: "workbuddy",
    group: "cn",
    role: "agent",
    kicker: "国内产品",
    title: "WorkBuddy",
    question: "腾讯这套助手的国内版、国际版、IDE 和 CLI，为什么不是一个开关？",
    summary: "写代码的循环和办公套件都能看见，但模型目录随版本变，自定义模型走 models.json。",
    blurb: "IDE 与 CLI 分开，国内版和国际版的模型目录也分开。",
    opening: "一个聊天窗口盖不住终端和办公",
    stuck: "想要终端里的长循环，又想要中文办公环境里的现成集成。只装一个聊天窗口，两头都不够。",
    layers: "IDE 负责图形里的改动。CLI 负责终端循环，这是它和国际上 Claude Code 用法靠近的地方。国内版和国际版的内置模型不是同一份名单：有没有 Claude、有没有国内模型，以你下载的那一版为准。自定义 OpenAI 风格模型写在 models.json，项目级可以盖过用户级。",
    widgets: [widget("layers", { items: "IDE|CLI|国内版模型目录|国际版模型目录", active: "1" })],
    task: "在 CLI 里改仓库，步骤和别的终端代理一样：读、改、给人看差异。要换成 DeepSeek、GLM 或 Kimi，在 models.json 里登记 url、apiKey 和 id，url 写到完整的 chat/completions。不要把密钥提交进仓库。",
    model: "内置目录随版本。自定义燃料来自你填的端点。国际版若内置了 Claude 或其他海外模型，那是产品打包，不是你用国内密钥「解锁」出来的。",
    data: "仓库在本机时，只有被读进请求的部分离开机器。办公套件若被接上，那些文档的边界要单独看，不要和源码的边界混成一句「都在腾讯」。",
    neighbor: "Trae 更强调开箱和国内模型的现成名单，公开对比里没有对等的 CLI。ZCode 更窄，集中在写代码。元宝做办公交付，不走这个编程循环。",
    switchWhen: "你没有 CLI 需求、只想要现成的国内模型，可以先看 Trae。你要的是智谱模型的官方代码代理，看 ZCode。你要幻灯片和表格，看元宝或豆包。",
    more: [links([{ href: "/tools/pairing#pair-workbuddy-switch", label: "在列表里换燃料" }])],
  }),
  tool({
    slug: "trae",
    group: "cn",
    role: "agent",
    kicker: "国内产品",
    title: "Trae",
    question: "字节这套编辑器的国内版和国际版，为什么不能共用一张模型表？",
    summary: "国内版能见到豆包、DeepSeek、GLM 这类名单。国际版是另一张表。终端长循环不要默认它有。",
    blurb: "国内版和国际版不是同一份模型目录。",
    opening: "编辑器里想直接用中文模型",
    stuck: "需要一个装上就能用中文模型写代码的编辑器，又不想先申请三家密钥。",
    layers: "它是 VS Code 一系的编辑器加代理。国内版的内置模型偏向豆包、DeepSeek、GLM。国际版的名单不同，而且不要假设海外模型一定还在。公开对比里它没有和 WorkBuddy 国际版对等的 CLI。层的名字以官网为准。",
    widgets: [widget("layers", { items: "国内版模型|国际版模型|编辑器里的代理|不要默认有 CLI", active: "0" })],
    task: "在编辑器里改一个驱动常量，让代理提出差异。需要「停在目录里连续读日志、改、再跑」的长循环时，若这一版仍然没有 CLI，就把仓库交给有 CLI 的客户端，而不是在编辑器里把同一句话重复十次。",
    model: "优先用你这一版内置的模型。能不能再填外部 Provider，看设置里有没有入口。没有入口就当它没有。",
    data: "和别的编辑器代理一样：本机仓库，被读到的片段进入当前模型提供方。国内版和国际版的提供方不是同一家的默认值。",
    neighbor: "WorkBuddy 把 CLI 当作明确的一层。Qoder 同时有 IDE、JetBrains 插件和 CLI。Trae 的优势是国内模型的开箱，不是终端形态。",
    switchWhen: "你的工作几乎都在终端里，换到有 CLI 的一章。你只是想要编辑器里的国内模型，并且接受没有那条命令行，就留在这里。",
  }),
  tool({
    slug: "qoder",
    group: "cn",
    role: "agent",
    kicker: "国内产品",
    title: "Qoder CN",
    question: "原来的通义灵码变成一系列产品之后，哪一个按钮才是「写代码」？",
    summary: "IDE、JetBrains、CLI 和云端代理是一系列。有人会把它写成 Qcoder。Credits 并不盖住每一个功能。",
    blurb: "阿里的一整系列：IDE、插件、CLI 和云端代理。",
    opening: "插件补全停在当前文件",
    stuck: "一个插件只能补全当前文件。工程级任务要拆步骤、要改很多文件，还要有人能在终端里叫起同一个代理。",
    layers: "Qoder CN 是阿里云这一系列的名字，2026 年 5 月由通义灵码更名而来。IDE、JetBrains 插件、CLI、面向办公的桌面形态和云端代理是并列的子产品。模型选择器里可以换 GLM、DeepSeek、Kimi、MiniMax 等，具体名单以控制台为准。Credits 是订阅额度，不自动等于每一项功能都无限次。",
    widgets: [widget("layers", { items: "IDE|JetBrains 插件|CLI|云端代理", active: "0" })],
    task: "日常改动留在 IDE 或 JetBrains 插件里。脚本和远程机器上的事走 CLI。需要脱离本机长时间跑的任务，再看云端代理那一个子产品，不要在 IDE 的输入框里假装自己有一台云电脑。",
    model: "系列内切换的是它接好的国内模型。这是产品内的搭配，仍然符合「代理不动、燃料可换」，只是换的菜单由它提供。额度用完后的行为和价格，看阿里云当时的计费说明，不写死在这里。",
    data: "企业版还会把知识库和审计放进来。个人仓库和公司知识库不是同一个边界。云端子产品的文件留在云上的环境里。",
    neighbor: "Trae 更像一个编辑器。WorkBuddy 的 CLI 叙事更靠近终端代理。Qoder 的特点是同一账号下的形态比较多，选错形态会以为功能丢了。",
    switchWhen: "你只用一个编辑器、不需要插件和云端，就不必为了系列完整而都打开。你要的是智谱自家的代码代理，去 ZCode，不必绕到这个选择器里再找 GLM。",
  }),
  tool({
    slug: "zcode",
    group: "cn",
    role: "agent",
    kicker: "国内产品",
    title: "ZCode",
    question: "智谱的代码代理，为什么不该被拉去写幻灯片？",
    summary: "默认燃料是 GLM。它负责仓库里的改动，办公交付交给豆包或元宝。",
    blurb: "面向写代码的代理，不是办公套件。",
    opening: "办公套件写不好仓库里的差异",
    stuck: "需要一个开箱就用国产模型改代码的代理，又不想先变成办公助手。",
    layers: "ZCode 是代码代理：补全、重构、测试这类仓库内工作。GLM 是默认燃料。模型设置若允许其他 Provider，那是额外的一档。做幻灯片、表格和长文档不是这一层。",
    widgets: [widget("layers", { items: "代码代理|默认 GLM|办公交付不在这里", active: "0" })],
    task: "把一个驱动模块的改动交给它，要求只动换算并补上检查。长上下文若是 GLM 这一侧的能力，可以一次放进较多日志，但仍要人看差异。做周报或幻灯片时离开这一章。",
    model: "默认 GLM。换 DeepSeek 或 Kimi 要看模型设置是否提供了字段，细节在搭配章，不要在代码任务里混进办公提示。",
    data: "源码请求去智谱或你另填的端点。不要把未公开的原理图整包丢进一个以聊天为界面的导出功能。",
    neighbor: "GLM 那一章是燃料。这里是车。WorkBuddy 和 Qoder 的车更能伸进办公或多种 IDE。豆包收费版是另一本账，买的常常是创作额度而不是这个代码循环。",
    switchWhen: "差异和测试是主要产出，留在这里。产出是文档或视频，去豆包或元宝。你已经有一套离不开的技能在 Claude Code 里，就把 GLM 接过去，而不是把技能重写成 ZCode 的提示。",
    more: [links([{ href: "/tools/pairing#pair-zcode-glm", label: "和 GLM 的默认搭配" }])],
  }),
  tool({
    slug: "doubao",
    group: "cn",
    role: "agent",
    kicker: "国内产品",
    title: "豆包收费版",
    question: "会员、创作额度和云存储，为什么是三笔账？",
    summary: "付费不是自动变成编程 IDE。图片和视频的额度，和仓库里的差异，不是同一个计数器。",
    blurb: "会员、创作额度、云存储要分开算。",
    opening: "做图额度用完，并不等于编程也该买这一档",
    stuck: "免费额度在做图或做视频时先用完，于是有人把「升级」理解成所有 AI 工作都该买这一档。",
    layers: "会员是身份和一部分能力的期限。创作额度包是一次性的用量，有自己的有效期，用完不结转的规则以协议为准。云存储是容量，不是模型更聪明。三笔可以同时存在，不能互相抵扣成「我已经买了编程代理」。",
    widgets: [widget("layers", { items: "会员期限|创作额度|云存储", active: "1" })],
    task: "做一版结构说明里的配图，先看创作额度。把配图存下来，看的是云存储。让一个代理去改固件仓库，这三笔账都不会自动出现差异视图。编程仍回到 Cursor、Claude Code、ZCode 或 WorkBuddy。",
    model: "豆包用的是字节一侧的模型。它出现在 Trae 国内版的名单里时，是 Trae 那个客户端在用它，不是豆包会员本身变成了 Trae。",
    data: "创作内容和云盘在产品自己的存储里。源码不要为了「会员已经付过」就同步进这只云盘。",
    neighbor: "元宝更偏向把任务交成办公文件。豆包这一档要先问你是不是在为图片、视频和存储付钱。两者都不是电路板工具。",
    switchWhen: "连续两周免费额度挡着交付，再考虑付费，并先算清额度包能不能在有效期内用完。主要工作是改代码，就不要用这一章的发票去证明代理已经买对了。",
  }),
];

export const freeChapters = [
  tool({
    slug: "opencode",
    group: "free",
    role: "agent",
    kicker: "免费",
    title: "OpenCode",
    question: "客户端开源，为什么模型通常仍要另算？",
    summary: "终端、桌面和 IDE 扩展是免费的程序。请求仍会到你选的那一家模型。",
    blurb: "开源代理，模型大多自备。",
    opening: "订阅编辑器把客户端和模型绑在一起",
    stuck: "不想把工作流绑死在某一个订阅编辑器上，又需要读文件、改文件、并行开几个会话。",
    layers: "终端界面、桌面应用和 IDE 扩展是三种门。模型层默认由你带：可以是它挑选过的一份清单，也可以是任意认协议的 Provider，包括本机。程序开源，不等于模型推理免费。",
    widgets: [widget("layers", { items: "终端|桌面|IDE 扩展|自备模型", active: "3" })],
    task: "在同一个仓库里开一个会话读手册，用 Kimi；再开一个会话改代码，用 DeepSeek。客户端不用换。若改用本机模型，两个会话的请求都可以不出机器，能力另说。",
    model: "官方表述是可以连接许多提供方，也有一份他们验证过的模型清单。Claude、GPT、Gemini 或国内兼容接口，都是「你去接」，不是安装时送的无限额度。",
    data: "OpenCode 自己的说法是不保存你的代码和上下文。这不阻止请求到达你选中的模型提供方。隐私边界在提供方，不在「开源」两个字上。",
    neighbor: "Claude Code 的循环更紧地绑着官方模型和技能生态。Freebuff 连模型一起用广告换。OpenCode 把客户端和账单拆开，所以搭配章里它的格子最多。",
    switchWhen: "你依赖某一家编辑器的索引和图形差异，回到 Cursor 或 Trae。你连模型密钥都不想管，并接受广告和数据条款，再看 Freebuff。",
    more: [links([{ href: "/tools/pairing#pair-opencode-deepseek", label: "三种燃料怎么换" }])],
  }),
  tool({
    slug: "freebuff",
    group: "free",
    role: "agent",
    kicker: "免费",
    title: "Freebuff",
    question: "不付订阅、不带密钥，模型的成本被放到了哪里？",
    summary: "广告支撑终端、桌面、网页、云仓库和聊天。提示词可能参与广告分析。",
    blurb: "用广告换模型，也可以挂上你已有的代理。",
    opening: "还没有订阅，也还不想先办五家计费",
    stuck: "想先跑起来一个编码代理，但没有国外订阅，也不想先办五家模型的计费。",
    layers: "CLI、桌面、网页应用、挂在 GitHub 仓库上的云代理，以及一个聊天。桌面还可以挂上你本机已经登录的 Claude Code 或 Codex，那部分模型不属于它赠送的目录。赠送目录里出现过的名字会变，以产品内列表为准。",
    widgets: [widget("layers", { items: "CLI|桌面|网页|云仓库|聊天", active: "0" })],
    task: "公开的小实验可以用它的代理直接改。工作仓库先问：提示词和代码片段能不能进入广告分析。若不能，就只把外层编排放在这里，里层仍走你自己的 Claude Code 或 Codex，或者干脆不用这一层。",
    model: "包含的模型由广告支付，所以名单和额度会随容量变化。挂上去的 Claude Code / Codex 仍用你原来的 Provider。这是两个 Agent 叠在一起的那种搭配。",
    data: "官方模式是文字广告。要假设提示词可能被用来决定广告，而不是假设和付费订阅同一条隐私条款。私有仓库、未公开的手册，默认不要进云端那一形态。",
    neighbor: "OpenCode 要你自己带模型，换来客户端不靠广告。本地运行连外部推理都省掉。Freebuff 省的是起步时的账单，不省审查。",
    switchWhen: "代码不能离开受控环境，就不要用它的云形态。你已经有订阅，只是想要一个免费的外层编排，可以挂里层，但外层仍看得到任务描述。",
    more: [links([{ href: "/tools/pairing#pair-stack-freebuff", label: "外层和里层各用各的模型" }])],
  }),
  tool({
    slug: "local-models",
    group: "free",
    role: "provider",
    kicker: "免费",
    title: "留在本机",
    question: "程序免费之外，还有哪条路能让代码不离开这台机器？",
    summary: "Ollama 一类本地运行时加上一个认兼容接口的客户端。推理变弱，是这条路的正文，不是脚注。",
    blurb: "权重在本机，客户端仍可以是 OpenCode 或其他代理。",
    opening: "外部接口再便宜，未公开的图和日志也不能送出去",
    stuck: "外部接口再便宜，未公开的日志和原理图也不能送出去。",
    layers: "本机运行时负责把权重跑起来，并常常提供一个兼容接口。客户端是 OpenCode，或任何允许改基址的代理。还有一些同样「程序免费、模型另算或本地」的客户端，例如只在终端里打补丁的工具，它们解决的是编辑，不是完整的代理循环。",
    widgets: [widget("layers", { items: "本机权重|兼容接口|代理仍在客户端", active: "0" })],
    task: "把 OpenCode 的提供方指到本机。让它读一段可以留在机器上的日志并改注释。需要很长的手册推理或很稳的工具调用时，不要假设本机小模型等于云上的代码模型。对不上，就把可公开的那一部分送出去，私有部分留在本地摘要里。",
    model: "Provider 是你自己的机器。没有按 token 的外部账单，有显存、速度和能力三笔本地成本。",
    data: "请求不去外部提供方。电脑若本身会被备份或共享，权重和仓库仍在那台电脑的安全边界里。",
    neighbor: "Freebuff 用广告把外部模型变得像免费。这里是把模型搬回家。搭配章里，它是 OpenCode 的一列，不是所有图形编辑器的默认列。",
    switchWhen: "本机模型开始稳定地编造寄存器地址，就把公开资料的推理交回云上的 Provider，改动仍由本机代理套用到仓库。不要为了「全程本地」接受一份不会被发现的错单位。",
    more: [links([{ href: "/tools/pairing#pair-opencode-ollama", label: "接到 OpenCode" }])],
  }),
];
