import { h2, links, p, tool, widget } from "./shape";

export const modelChapters = [
  tool({
    slug: "deepseek",
    group: "models",
    role: "provider",
    kicker: "国内模型",
    title: "DeepSeek",
    question: "一家模型同时有对话和代码两种用法时，客户端到底在买什么？",
    summary: "DeepSeek 是燃料。兼容接口意味着基址、密钥和模型名，不意味着每个客户端功能都会自动出现。",
    blurb: "对话模型和代码模型，加上一套兼容接口。",
    stuck: "人们把模型名字当成一个可以打开的编辑器。打开之后没有仓库、没有差异，是因为那一截本来就不是模型该有的。",
    layers: "对话模型负责回答和起草。代码向的模型把更多能力放在改程序上。兼容接口是第三层：你的客户端用约定的地址去调用它。三层可以来自同一家，却对应三种不同的用法。",
    widgets: [widget("layers", { items: "对话模型|代码模型|兼容接口", active: "2" })],
    task: "读一份串口日志并解释误差，用对话模型就够。要在仓库里改换算并跑检查，把代码模型接到一个真正的代理上，让代理去读文件。只拿到接口、没有代理，你仍得自己粘贴代码。",
    model: "它自己就是 Provider。OpenAI 风格的兼容，通常是一个基址、一把你申请的密钥、一个模型名。工具调用是否能用，要看该模型是否声明支持，以及客户端是否把工具报文转对了。",
    data: "请求内容到 DeepSeek 的接口所在的那一侧。仓库本身不会搬家，除非客户端把文件读进了请求。",
    neighbor: "GLM 同样能做燃料，并且和 ZCode 绑得更紧。Kimi 更常被拿来一次放进很长的材料。接进哪个客户端，不由这三家里的任何一家单独决定。",
    switchWhen: "材料长到普通窗口装不下，试 Kimi 那种长上下文。你已经在用智谱的代码代理，并且不想再维护第二套端点，就让 GLM 留在 ZCode 里。",
    more: [links([{ href: "/tools/pairing#pair-claude-code-deepseek", label: "接到 Claude Code 或别的代理" }])],
  }),
  tool({
    slug: "glm",
    group: "models",
    role: "provider",
    kicker: "国内模型",
    title: "GLM",
    question: "智谱的模型，和智谱的代码代理，是同一件产品吗？",
    summary: "GLM 是燃料。ZCode 是用这桶燃料跑起来的一辆车，车也可以换油。",
    blurb: "模型是燃料，ZCode 只是其中一辆车。",
    stuck: "只记得产品名，会把「换一个模型」做成「卸载整个代理」。代理里的技能、仓库说明和差异视图，不在模型的权重里。",
    layers: "GLM 是一组模型。ZCode 是面向写代码的代理，默认烧这组模型。同一套兼容接口还能接到别的认这套协议的客户端。办公交付不是这辆车的本职，那种任务去豆包或元宝。",
    widgets: [widget("layers", { items: "GLM 模型|ZCode 这辆车|其他认协议的客户端", active: "0" })],
    task: "在 ZCode 里改固件注释和换算，走的是默认搭配。若你更习惯 Claude Code 的循环，就把 GLM 的端点指过去，技能仍留在 Claude Code。两次都要核对工具调用真的发出去了，而不是只核对聊天能通。",
    model: "申请的是智谱一侧的密钥和模型名。ZCode 里可以不手填。别的客户端里要手填基址和模型名。",
    data: "请求到你填的那个端点。用官方客户端时，端点就是智谱的。不要把密钥写进仓库说明。",
    neighbor: "DeepSeek 没有一个和 ZCode 对等的「官方代码车」叙事，它更常作为各家客户端的燃料。Kimi 的特长在长度，不在这一辆车。",
    switchWhen: "你要的是办公文件而不是差异，离开 ZCode。你要的是终端里那套技能，就保留技能，只把燃料换成 GLM。",
    more: [links([{ href: "/tools/zcode", label: "ZCode 这辆车" }, { href: "/tools/pairing#pair-zcode-glm", label: "默认搭配" }])],
  }),
  tool({
    slug: "kimi",
    group: "models",
    role: "provider",
    kicker: "国内模型",
    title: "Kimi",
    question: "上下文特别长，适合把什么一次放进去？",
    summary: "长材料是它的理由。它仍然是模型，不是一个编程客户端。",
    blurb: "适合一次放进手册、日志和长规格。",
    stuck: "普通窗口装不下一份寄存器手册加一天的串口日志。来回截断之后，模型会把两截日志当成同一时刻。",
    layers: "长上下文是模型能力。聊天窗口是一种用法。把它接到代理上，是另一种用法：代理决定读哪一截，模型负责在很长的材料里回答。不要因为它能聊，就把它当成已经会改仓库。",
    widgets: [widget("layers", { items: "长上下文|手册与日志|不是客户端", active: "1" })],
    task: "把一份手册里关于采样时序的章节和一段日志一起交给它，让它指出单位不一致的地方。真正改文件仍交给带着仓库的代理。代理可以选择在「读长材料」这一步换用 Kimi，改代码时再换回别的模型。",
    model: "Kimi 是 Provider。接入方式仍是客户端认的基址、密钥和模型名。长上下文不等于工具调用一定可用，这一项要单独核对。",
    data: "你放进窗口或请求里的手册和日志会到这一侧。整本手册若有未公开的部分，先决定该不该送出，而不是先决定模型聪不聪明。",
    neighbor: "DeepSeek 和 GLM 更能扮演「每天改代码的燃料」。Kimi 适合作为同一次工作里的另一档：材料很长的那一档。",
    switchWhen: "材料并不长，就不必为长度付钱或换端点。材料长，但你不能把它送出本机，长度也救不了这个约束，去看留在本机。",
    more: [links([{ href: "/tools/pairing#pair-opencode-kimi", label: "在同一个代理里换成它" }])],
  }),
  tool({
    slug: "wiring",
    group: "models",
    role: "method",
    kicker: "国内模型",
    title: "接进客户端",
    question: "DeepSeek、GLM 或 Kimi 的密钥，要落到四个客户端的哪一个字段？",
    summary: "四扇门：Claude Code 的兼容端点、ChatGPT / Codex 的自定义提供方、WorkBuddy 的 models.json、ZCode 的模型设置。",
    blurb: "四条公开路径，外加用一个 AI 给另一个写草稿。",
    stuck: "文档在模型厂商的网站上，要改的文件在另一个客户端里。人来回抄字段时，最容易把基址抄成聊天地址，或把模型名抄成展示名。",
    layers: "每一扇门只认自己的字段。Claude Code 看兼容端点。ChatGPT / Codex 只在它暴露了自定义提供方时才有这一栏。WorkBuddy 把自定义模型写进 models.json，地址一般要到完整的 chat/completions。ZCode 用它自己的模型设置。四扇门都不要填真实密钥到教程或仓库里。",
    widgets: [widget("protocol"), widget("advisor")],
    task: "先选定 DeepSeek、GLM 或 Kimi。在动画里看它落进哪一扇门。然后用一个已经能对话的代理当顾问：把官方字段说明交给它，让它写出目标客户端的草稿。草稿里只有基址、模型名和每个字段的含义。",
    model: "顾问用它自己的模型。被配置的客户端用你正要接上的那一家。这就是两个 Provider 同时存在：一个负责读文档，一个负责随后的代码循环。",
    data: "密钥停在人这一侧，由人粘贴进客户端的私密位置。顾问不该申请密钥，不该转存别的产品的登录态，也不该猜一个能用的钥匙。把登录态转发出来的第三方工具，可能违反服务条款，也不适合放工作仓库，这里不写接法。",
    neighbor: "搭配章讲「谁可以和谁一起工作」。这一章只讲字段落在哪，以及怎样让另一个 AI 帮你填对字段。",
    switchWhen: "最小请求失败时，先分清是协议不匹配、模型名不被认识，还是密钥不对。三种失败不是同一种按钮可以修好的。",
    more: [
      links([{ href: "/tools/pairing", label: "看完整的交错例子" }]),
      h2("顾问只写草稿"),
      p("常见的做法是：Cursor、Claude Code 或 ChatGPT 已经开着。你把 DeepSeek、智谱或 Kimi 文档里关于基址和模型名的那几段交给它，说明目标是 Claude Code 的环境变量，或 WorkBuddy 的 models.json。它返回草稿。你自己到厂商控制台申请密钥并贴上。然后发一次最短的请求，核对三件事：模型名是否被认出来、工具调用有没有真正发出去、报错属于格式还是密钥。"),
    ],
  }),
];
