import type { ToolChapter } from "@/lib/types";
import { h2, links, p, widget } from "./shape";

export const pairingChapter: ToolChapter = {
  slug: "pairing",
  group: "models",
  role: "method",
  kicker: "国内模型",
  title: "交错搭配",
  question: "Provider 提供推理，Agent 提供循环。为什么两者可以换着配？",
  summary: "换模型时，仓库循环和技能通常还在。换客户端时，同一把模型钥匙可以再接一次。",
  blurb: "模型、代理和技能是三层，可以交错。",
  updated: "2026-10-05",
  blocks: [
    h2("出厂搭配把模型和客户端焊在一起"),
    p("出厂搭配让人以为 Claude Code 只能用 Claude，DeepSeek 只能打开 DeepSeek 的网页。于是换一个任务就要换一整套习惯，技能和仓库说明也跟着丢。"),
    h2("它分成哪几层"),
    p("Provider 负责推理：下一个词、工具调用的参数、对长材料的阅读。Agent 负责循环：读仓库、改文件、跑命令、必要时看屏幕。Skill 和 MCP 挂在 Agent 上。换 Provider，循环和技能还在。换 Agent，同一把密钥可以接到另一个认这套协议的客户端。"),
    widget("pair-board"),
    h2("一次任务怎么走"),
    p("先选代理，因为它决定你看不看得到差异、技能放在哪。再选这一步的模型：读长手册、改代码、或必须留在本机，可以是三种燃料。最后才填端点。填的方法在接入章，用另一个已经能对话的 AI 写草稿，密钥仍然人贴。"),
    h2("同一个 Agent，换 Provider", "pair-claude-code-deepseek"),
    p("Claude Code 的循环、项目说明和技能不动，只把兼容端点从官方 Claude 改到 DeepSeek。模型名用 DeepSeek 文档里的名字，密钥用你自己的。改完用一次最小请求确认工具调用真的发出去，而不是只确认「能聊天」。"),
    h2("GLM 接在同一个循环上", "pair-claude-code-glm"),
    p("同一套 Claude Code，燃料换成 GLM。ZCode 不再是这桶燃料的唯一车子。若工具调用失败，先核对智谱要求的模型名和报文，不要先重装代理。"),
    h2("Kimi 接在同一个循环上", "pair-claude-code-kimi"),
    p("手册和日志很长的那一步，可以把 Claude Code 的端点临时换成 Kimi。改代码的下一步若更适合别的模型，再换回来。长上下文是这一档的理由，不是所有步骤的默认值。"),
    h2("OpenCode 读长材料", "pair-opencode-kimi"),
    p("OpenCode 是同一个终端代理。读一本很长的手册时用 Kimi，代理的读文件和命令不用换一套。"),
    h2("OpenCode 改代码", "pair-opencode-deepseek"),
    p("改仓库的那一程改接 DeepSeek。客户端仍是 OpenCode，所以主题、快捷键和并行会话都还在，变的是请求去了哪一家。"),
    h2("OpenCode 接其他兼容接口", "pair-opencode-any"),
    p("OpenCode 的设计就是自备模型。GLM 只要提供它认的兼容接口，就可以成为第三档，不必等一个官方插件。"),
    h2("代码留在本机", "pair-opencode-ollama"),
    p("把 OpenCode 的提供方改到本机运行的模型。循环还在，请求不再发往外部。能力通常变弱，这是留在机器里的代价，不是白捡的同款。"),
    h2("Cursor 的自定义模型", "pair-cursor-custom"),
    p("Cursor 的索引和差异还在。若当前版本有自定义模型入口，DeepSeek、GLM 或 Kimi 可以接进来当燃料。没有这一栏，就不要假装它有。入口以你安装的版本为准。"),
    h2("WorkBuddy 的模型列表", "pair-workbuddy-switch"),
    p("WorkBuddy 可以在 models.json 里同时登记 DeepSeek、GLM 和 Kimi。按任务在列表里切换。地址要写到它要求的完整路径，模型名用厂商的 id，不要用聊天窗口里的昵称。"),
    h2("ChatGPT / Codex 的自定义提供方", "pair-chatgpt-custom"),
    p("只有客户端真的露出自定义提供方时，DeepSeek、GLM 或 Kimi 才能从这扇门进来。没有这一栏，编码代理就还是原厂模型。不要用非官方的登录态转发去假装有这扇门。"),
    h2("ZCode 的默认燃料", "pair-zcode-glm"),
    p("ZCode 开箱烧的是 GLM。这是默认搭配，不是唯一的物理定律。写代码时先用这套，少维护一个端点。"),
    h2("ZCode 的模型设置", "pair-zcode-custom"),
    p("若 ZCode 的模型设置允许别的提供方，DeepSeek 或 Kimi 可以按它的文档填进去。GLM 仍是默认。办公文件不要因此改到 ZCode 里做。"),
    h2("两个 Agent 叠在一起", "pair-stack-cursor-claude"),
    p("Cursor 里的代理当顾问，读的是 DeepSeek 或智谱的字段说明，用的是 Cursor 当前的模型。它写出 Claude Code 的配置草稿。真正改仓库的循环跑在 Claude Code 里，燃料是 DeepSeek。顾问和工人不是同一个 Provider。"),
    h2("外层编排，里层仍是原来的代理", "pair-stack-freebuff"),
    p("Freebuff 可以做外层，把任务分给已经买了的 Claude Code 或 Codex。外层用它广告支撑的模型，里层用你自己的订阅。两边的模型可以不是同一家。工作仓库要不要进外层，先看 Freebuff 那一章的数据说明。"),
    h2("网页和仓库不在同一个代理里", "pair-stack-cloud-local"),
    p("Manus 或腾讯元宝用浏览器打开芯片手册的公开页，把时序摘出来。本机的 Claude Code 用另一个 Provider 把摘录改进固件仓库。云端代理不需要你的编译器，本地代理也不需要云浏览器的登录态。"),
    h2("手不跟着模型走", "pair-hands"),
    p("Computer Use 和 Browser Use 是 Agent 的手。换成 DeepSeek 或 Kimi 之后，还能不能看屏幕、开网页，取决于这个客户端有没有接上这只手，而不是取决于模型品牌。"),
    h2("模型从哪来"),
    p("表里的每一格都是一条「代理仍在，燃料换了」或「燃料仍在，代理换了」。格子是空的，就是这篇没有把它写成可用搭配，不是暗示你去找非公开的转发。"),
    h2("数据留在哪"),
    p("每次只有当前请求里的内容会到那一个 Provider。叠两个代理时，手册网页的内容和仓库里的文件可以去两家不同的地方。这个分裂是你该主动选择的，不是事故之后才发现的。"),
    h2("和邻章差在哪"),
    p("接入章负责字段。这一章负责场景。各个产品章不再把对方写成唯一搭档，只留回这里。"),
    h2("什么时候该换"),
    p("工具调用不通，先回到接入章对协议。能力突然变差，先看是不是换燃料换得太狠，而不是先怀疑技能丢了。技能还在不在，看客户端的技能目录，不看模型名字。"),
    links([
      { href: "/tools/wiring", label: "字段怎么填" },
      { href: "/tools/computer-use", label: "手在桌面上" },
      { href: "/tools/browser-use", label: "手在浏览器里" },
    ]),
  ],
};
