import { figure, h2, links, p, table, ul } from "@/lib/blocks";
import type { Block } from "@/lib/types";

const shot = (name: string, alt: string, caption: string) => figure(`/shots/${name}.png`, alt, caption);

export const sheets: Record<string, Block[]> = {
  cursor: [
    h2("原生模型和两个用量池"),
    p("Cursor 的定价文档把用量分成两个按月重置的池，而不是按「一次 Agent 请求」计数。Cursor Models 池覆盖它标成第一方的 Grok 4.7、Grok 4.6、Grok 4.5 和 Composer 2.5，含各自的 Fast 档。Other Models 池按第三方模型自己的 API 价计，文档里列着 Anthropic 的 Claude、Google 的 Gemini、OpenAI 的 GPT、智谱 GLM、月之暗面 Kimi，以及 Meta 的 Muse Spark。选哪个名字，决定扣哪一个池。"),
    shot("cursor-models", "Cursor 文档里的模型与价格页", "2026-10-05 打开的 Cursor Models & Pricing。左侧还有 Agent、Plan、Debug、Design Mode，以及 Grok Bot、Skills、MCP。价格以该页表格为准。"),
    table(
      ["池", "文档里点名的模型", "怎么扣"],
      [
        ["Cursor Models", "Grok 4.7 / 4.6 / 4.5，Composer 2.5，含 Fast 与长上下文档", "套餐内额度更大；文档给了每百万 token 的输入、缓存读、输出价"],
        ["Other Models", "Claude、Gemini、GPT、GLM、Kimi、Muse Spark 等", "按该模型 API 价从第二个池扣；用尽后可按需续费"],
      ],
    ),
    h2("套餐和特色菜单"),
    p("个人方案在文档里写成 Start（仅印度，约 ₹649/月，只有 Cursor Models 池，不能开 Fast，也不能调 effort）、Pro（$20/月）、Pro Plus（$60/月）、Ultra（$200/月）。后三档两个池都有，并写明不限量的 Tab 补全、Bugbot 和 Cloud Agents。团队席位另有 Standard 与五倍用量的 Premium。Teams 上使用第三方模型还会加一笔 Cursor Token Rate。Auto 有 Cost、Balance、Intelligence 三档，账单按实际路由到的模型计算。旧的按请求计费方案才有 Max Mode。"),
    ul([
      "Tab：光标处补全，和 Agent 不是同一个用量故事。",
      "Agent：跨文件改动。文档侧栏把它和 Review、Planning、Debugging、Design Mode 并列。",
      "Cloud Agents：合上笔记本之后仍可跑的代理，和本地 Agent 共用账号体系，不共用同一台电脑。",
      "Skills、Hooks、MCP、Subagents：侧栏里的扩展，不是模型名字。",
    ]),
    p("改电流环时，日常补全可以留在 Composer 或 Grok 的 Cursor Models 池里。需要对照长手册、或指定 Claude / GPT 时，才进入 Other Models，并看着用量仪表，而不是等它突然停。"),
    links([{ href: "https://cursor.com/docs/models-and-pricing", label: "Cursor Models & Pricing" }]),
  ],
  "chatgpt-codex": [
    h2("对话池和编码代理不是同一个菜单"),
    p("ChatGPT 是对话产品。Codex 是其中能看见仓库、改文件、跑命令的那一层。两边可以在同一个账号下，模型却不必是同一次选择：聊天里换一个推理更强的模型，不会自动变成仓库里的那次代理运行。官方帮助页把用量放在账号自己的用量视图里，不同订阅档共享或拆分的方式会改，不要把某一年的「每五小时多少条」抄成永久配额。"),
    h2("工作模式"),
    ul([
      "对话：解释一段采样日志、对照两种滤波，产出留在聊天里。",
      "编码代理：进入仓库，留下差异。没有这一层时，聊天里的死区数值还不是源码。",
      "自定义提供方：只有设置里真的出现这一栏，DeepSeek、GLM、Kimi 才能从这里进来。",
    ]),
    p("特色菜单是对话线程、项目文件和编码代理的任务视图。不要在聊天输入框里找 Tab 补全，那是编辑器产品的菜单。用量以订阅页和客户端里的剩余额度为准，这篇不写死条数。"),
    links([{ href: "https://openai.com/", label: "OpenAI 产品页" }]),
  ],
  "claude-code": [
    h2("原生模型"),
    p("用 Anthropic 账号登录时，模型菜单来自 Claude 家族。帮助中心让你用 /model 查看当前账号实际可选的名字，并按任务在更强的推理档和更省的日常档之间切换。子任务可以单独指定更轻的模型。具体代号随账号和日期变化，以 /model 列出的为准，而不是以教程里的一张旧表为准。"),
    shot("claude-modes", "Claude Code 权限模式文档", "权限模式页把 default、acceptEdits、plan、auto、dontAsk、bypassPermissions 列成一张表。这是工作模式，不是模型名。"),
    h2("用量"),
    p("Pro、Max、Team、Enterprise 的用量和网页上的 Claude 共享，不是终端另有一个无限池。/usage 能看到方案用量；API 密钥用户没有同一套订阅上限，但 /cost 对得上控制台账单。上下文满和用量满是两件事：前者用 /compact 或 /clear，后者要等窗口重置、换更轻的模型，或按提示改用 API 额度。"),
    h2("权限模式这条特色菜单"),
    table(
      ["模式", "不询问就做的事", "适合"],
      [
        ["default", "读取", "每一步都要自己看"],
        ["acceptEdits", "读取、改文件和常见文件命令", "你正在看差异"],
        ["plan", "读取，以及自动模式下被分类器放行的命令", "先查清再改死区"],
        ["auto", "其余动作，带后台安全检查", "长任务"],
        ["dontAsk", "只有预先允许的工具", "锁死的脚本"],
        ["bypassPermissions", "全部", "隔离的容器，不是日常开发机"],
      ],
    ),
    p("Shift+Tab 或 /plan 进入计划模式：可以读仓库、写计划，不直接改源码。改三相PWM 或死区之前，先用这一模式列出要碰的文件。/effort 或 /model 里的力度影响思考开销，思考 token 按输出计。"),
    links([{ href: "https://code.claude.com/docs/en/permission-modes", label: "Permission modes" }]),
  ],
  antigravity: [
    h2("几层产品，各自的模型"),
    p("Antigravity 不是一个输入框。公开材料把它拆成桌面指挥台、写代码的 IDE、CLI，以及跑在托管环境里的智能体。托管智能体的文档写过默认使用 Gemini 系列，并允许在配置里换底层模型。桌面和 IDE 里可选的名字以当时的模型选择器为准，不要把 Gemini 文档上的价目表当成桌面订阅的唯一账单。"),
    h2("特色菜单是工件，不是另一条聊天"),
    ul([
      "指挥台：同时看多个代理走到哪一步。",
      "IDE：仓库和差异。",
      "CLI：终端里的同一类循环。",
      "工件：计划、差异、截图和录屏，用来给人审。",
      "托管环境里的浏览器和终端：机制上接近 Browser Use，权限在对方的沙箱里。",
    ]),
    p("用量按你使用的那一层分别看：IDE 订阅、CLI 额度和 API 上的托管智能体不是同一个计数器。地区和预览资格以 Google 的产品页为准。"),
    links([{ href: "https://antigravity.google/", label: "Antigravity" }]),
  ],
  deepseek: [
    h2("官方 API 上的两个名字"),
    p("2026-10-05 打开的中文价格页把模型收成两列：deepseek-flash，版本写成 DeepSeek-V4.1-Flash；deepseek-v4-pro，版本写成 DeepSeek-V4-Pro-0813。旧名 deepseek-v4-flash 仍可调用，但页注写明由 V4.1-Flash 提供服务，并按 Flash 计价。两列都支持思考与非思考（默认思考），上下文 1M，最大输出 384K，支持 Tool Calls 和 Anthropic 格式。图像理解一栏 Flash 支持、Pro 不支持。"),
    shot("deepseek-price", "DeepSeek 中文价格页", "同一页左侧把 Claude Code、Codex、OpenCode、WorkBuddy、Qoder 列成接入入口。高峰时段写的是工作日 9:00–12:00 与 14:00–18:00。"),
    table(
      ["项目", "deepseek-flash", "deepseek-v4-pro"],
      [
        ["OpenAI 基址", "https://api.deepseek.com", "同一个基址"],
        ["Anthropic 基址", "https://api.deepseek.com/anthropic", "同一个基址"],
        ["上下文 / 最大输出", "1M / 384K", "1M / 384K"],
        ["并发", "页上为 2500", "页上为 500"],
        ["价格", "空闲约为高峰的一半，分缓存命中与未命中", "同左，单价更高"],
      ],
    ),
    p("对话网站和 API 不是同一个池。聊天会员不能代替 API 余额。扣费先用赠送余额，再用充值余额。页上保留调价权利，所以表里的元数以你打开时的格子为准，上面只固定那些没有争议的结构。"),
    links([{ href: "https://api-docs.deepseek.com/zh-cn/quick_start/pricing", label: "DeepSeek 模型与价格" }]),
  ],
  glm: [
    h2("开放平台上的旗舰，和 ZCode 里的燃料"),
    p("智谱 BigModel 价格页把 GLM-5.3 标成旗舰文本模型：上下文 1M，输入 8 元/百万 tokens，输出 28 元/百万 tokens，缓存命中 2 元，缓存存储限时免费，输入模态是文本。旁边的 GLM-5.3-Flash 是多模态，输入 0.8 元、输出 2.8 元、缓存命中 0.23 元，上下文同样 1M，能吃图片、视频、文件和文本。页面向下还能看到 GLM-5.2，输入同样标着 8 元。这些是 API 价，不是 ZCode 订阅里的「无限」。"),
    shot("glm-price", "智谱 BigModel 价格页", "旗舰卡片上的上下文和单价。更下面的模型和服务会随页面更新。"),
    p("ZCode 文档把 GLM Coding Plan 写成在 ZCode 里跑 GLM 的推荐方式：国内账号走 BigModel，海外走 Z.ai。套餐用积分，并写过周用量额度，Pro / Max 相对 Lite 有倍数关系，旧的权益差以套餐改版说明为准。不用套餐时，可以改用 API Key，编码端点是 https://open.bigmodel.cn/api/coding/paas/v4 ，通用端点是 https://open.bigmodel.cn/api/paas/v4 。"),
    h2("思考档位"),
    p("ZCode 的模型设置里，GLM-5.3 的档位是 low / high / max，默认 max；GLM-5.2 是 nothink / high / max，默认 max。档位改变的是这一次推理的力度和消耗，不是换成另一家公司的模型。"),
    links([
      { href: "https://www.bigmodel.cn/pricing", label: "BigModel 价格" },
      { href: "https://zcode.z.ai/cn/docs/configuration", label: "ZCode 连接模型" },
    ]),
  ],
  kimi: [
    h2("开放平台列表和产品里的 K3 不是同一扇门"),
    p("2026 年 10 月打开的 Kimi 开放平台模型文档列出 kimi-k2.7-code、kimi-k2.6、kimi-k2.5，上下文都写着 256K，并注明更早的 kimi-k2 系列已下线。与此同时，Cursor 的价格表和 Qoder 的模型表都出现了 Kimi K3，上下文可以到 1M，价格更高。所以「Kimi」这个牌子在聊天产品、开放平台和别人客户端的菜单里，名字并不自动对齐。接入时要抄你拿到密钥的那一页上的 model id。"),
    table(
      ["出现的地方", "公开点名的名字", "适合的材料"],
      [
        ["开放平台文档", "kimi-k2.7-code、kimi-k2.6、kimi-k2.5", "256K 上下文里的代码和长文本"],
        ["Cursor / Qoder 的菜单", "Kimi K3、Kimi K2.7 Code", "按那家客户端的倍率和上下文档"],
      ],
    ),
    p("长上下文适合一次放进寄存器章节和一段串口，不适合当成已经会改仓库。Kimi 没有自己的死区编辑器。用量在开放平台是充值后的 token 账；在别人的 IDE 里则是那家的 Credits 或订阅池。"),
    links([{ href: "https://platform.kimi.com/docs/models", label: "Kimi 模型列表" }]),
  ],
  wiring: [
    h2("四扇门各自要抄的字段"),
    p("DeepSeek 的价格页自己把 Claude Code、Codex、OpenCode、WorkBuddy、Qoder 放在「接入 Agent 工具」里。这是厂商承认的门，不是教程发明的。每扇门仍只认自己的字段：基址、密钥、模型 id、是否走 Anthropic 格式。DeepSeek 同时给了 OpenAI 基址和 /anthropic 基址，抄错格式就会表现为工具调用发不出去。"),
    table(
      ["客户端", "公开配置位置", "模型 id 从哪抄"],
      [
        ["Claude Code", "兼容端点的环境变量", "厂商价格页上的 id，不要抄展示名"],
        ["ChatGPT / Codex", "设置里若有自定义提供方", "同一份 id"],
        ["WorkBuddy", "models.json 的 url、apiKey、id", "url 写到它要求的完整 chat/completions"],
        ["ZCode", "添加供应商，或 API Key 模式", "智谱用文档里的 paas 端点；Kimi 用其 Anthropic 兼容地址"],
      ],
    ),
    p("用量仍然记在提供方账上。客户端套餐不会因为你填了一个基址就变成那家模型的无限额度。顾问 AI 只能根据这些公开字段写草稿，密钥由人从控制台复制。"),
    links([{ href: "https://api-docs.deepseek.com/zh-cn/quick_start/pricing", label: "页内的接入入口" }]),
  ],
  pairing: [
    h2("搭配改变的是账单落在哪一池"),
    p("Claude Code 的权限模式还在，燃料换成 DeepSeek 之后，/usage 那套 Anthropic 订阅条可能不再是这笔推理的账单，账单改到 DeepSeek 的余额。Cursor 里选 GLM，扣的是 Other Models 池，不是 Cursor Models 池。OpenCode 自己往往不设池，池在你选的提供方。把这些池画进搭配表，才不会把「能连上」当成「还在用原来的套餐」。"),
    ul([
      "同一代理换燃料：模式和技能留在客户端，单价改到新的价格页。",
      "同一燃料换代理：GLM 的 8 元/28 元 API 价不会因为放进 ZCode 套餐就按次显示，套餐用积分。",
      "两个代理叠用：外层广告产品和里层订阅各算各的。",
    ]),
  ],
  workbuddy: [
    h2("菜单里同时有目录模型和自定义模型"),
    p("WorkBuddy 的 IDE 与 CLI 是两种入口。国内版和国际版内置的模型目录不是同一张纸。腾讯云开发者社区的一篇说明列举过 Auto、混元 Hy3、GLM、MiniMax、Kimi 和 DeepSeek，并提到夜间时段的折扣。那是一篇解读，不是设置界面的契约。你本机下拉里的名字，以客户端为准。"),
    p("自定义模型走 models.json。文档要求 url 写到完整的 chat/completions，并可以标记是否支持工具调用和图像。项目级文件盖过用户级。Credits 是另一本账，用来支付它定义的文件处理和推理，不同模型的单次消耗不同。Coding Plan、Token Plan 和客户端订阅可能同时存在，不要假设扣的是同一格。"),
    h2("适合的工作模式"),
    ul([
      "IDE：看着差异改驱动。",
      "CLI：在目录里做长循环。",
      "办公连接：文档和邮箱，和源码的数据边界分开。",
    ]),
    links([{ href: "https://cloud.tencent.com/document/product/1831/134513", label: "models.json 配置指南" }]),
  ],
  trae: [
    h2("国内版和国际版是两本模型菜单"),
    p("Trae 是字节的编辑器加代理。国内版公开对比里常见豆包、DeepSeek、GLM；国际版是另一份名单，而且不要假设某一家海外模型一直还在。没有在公开对比里看到和 WorkBuddy 对等的 CLI。因此它的特色菜单是编辑器里的对话和代理，不是终端里的斜杠命令大全。"),
    p("用量随你下载的那一版：有的档位用免费额度，有的用订阅。模型选择器里看不到的名字，就不要用兼容基址去猜。需要长循环时，把仓库交给有 CLI 的客户端，而不是在编辑器里把同一句指令重复十次。"),
    links([{ href: "https://www.trae.ai/", label: "Trae" }]),
  ],
  qoder: [
    h2("Credits 倍率是它自己的菜单，不是厂商 API 价"),
    p("Qoder CLI 文档的模型表用 Credits 倍率，而不是元/百万 tokens。2026 年文档里的一页写着：Qwen3.8-Max 与 Qwen3.7-Max 为 0.5×，Qwen3.7-Plus 为 0.1×，Kimi-K3 为 0.8×，Kimi-K2.7-Code 为 0.3×，GLM-5.3 与 GLM-5.2 为 0.6×，DeepSeek-V4-Pro 为 0.8×，DeepSeek-V4-Flash 为 0.3×，MiniMax-M3 为 0.2×。上下文档有 200K、400K、1M，思考强度有 low / medium / high / xhigh 或 low / high / max，视模型而定。文档写明倍率可能随服务端变，以 /model 和 --list-models 为准。"),
    table(
      ["模型", "文档中的 Credits 倍率", "文档中的上下文"],
      [
        ["Qwen3.7-Plus", "0.1×", "200K / 400K / 1M"],
        ["MiniMax-M3", "0.2×", "200K / 400K / 1M"],
        ["DeepSeek-V4-Flash、Kimi-K2.7-Code", "0.3×", "Flash 到 1M；K2.7-Code 写的是 256K 与 Fast"],
        ["Qwen3.8-Max、Qwen3.7-Max", "0.5×", "200K / 400K / 1M"],
        ["GLM-5.3、GLM-5.2", "0.6×", "200K / 400K / 1M"],
        ["Kimi-K3、DeepSeek-V4-Pro", "0.8×", "200K / 400K / 1M"],
      ],
    ),
    p("个人版还允许用自己的密钥接入阿里云百炼、DeepSeek、智谱、Kimi、MiniMax、小米 MIMO。那时候账单回到厂商，不再按上表的 Credits 倍率。IDE、JetBrains、CLI 和云端代理是不同形态，Credits 不一定覆盖每一种无限次使用。原名通义灵码。"),
    links([{ href: "https://docs.qoder.com/zh/cli/model", label: "Qoder 模型与推理强度" }]),
  ],
  zcode: [
    h2("连接模型这一个菜单"),
    p("ZCode 文档把连接方式分成 GLM Coding Plan（国内 BigModel / 海外 Z.ai）和 API Key，以及第三方供应商。欢迎页三个按钮就是这三选一。侧栏同时列出 Agent、调试器、Wiki、Memory、远程、MCP、Skill、Hooks。这些是工作模式，不是额外的模型。"),
    shot("zcode-config", "ZCode 连接模型与套餐", "推荐 GLM Coding Plan，并给出第三方供应商和 API Key。思考档位在同一套文档的后面。"),
    p("默认燃料是 GLM。文档里的思考档位：GLM-5.3 为 low / high / max，GLM-5.2 为 nothink / high / max，Kimi K3 为 low / high / max，DeepSeek V4 为 high / max。第三方按 Anthropic 或 OpenAI 协议添加，Kimi 的例子用 https://api.moonshot.cn/anthropic ，模型 id 要手填。套餐额度用积分和周用量，API Key 用智谱或你添加的那家的余额。办公文件不是这个菜单的产出。"),
    links([{ href: "https://zcode.z.ai/cn/docs/configuration", label: "ZCode 连接模型" }]),
  ],
  doubao: [
    h2("三本账，没有编程代理的模式开关"),
    p("豆包收费版要分开看会员期限、创作额度包和云存储。会员是身份和一部分能力的期限。额度包是一次性用量，有自己的有效期，过期规则以购买页为准。云存储是容量。三本账都不等于仓库差异视图，也不等于 Trae 里那个豆包模型选项。Trae 国内版可以调用豆包模型，那是 Trae 的菜单。"),
    p("适合的使用场景是配图、视频和需要存下来的生成结果。改 PWM 死区仍回到编程代理。价格和额度数字只在客户端的购买页上确认。"),
    links([{ href: "https://www.doubao.com/", label: "豆包" }]),
  ],
  opencode: [
    h2("客户端免费，模型池在你选的提供方"),
    p("OpenCode 官网写的是开源编程代理，内置免费模型，或连接任意提供商，包括 Claude、GPT、Gemini。安装命令是一条 curl。功能列表写着 LSP、同一项目里的多会话、会话分享、用 GitHub 登录走 Copilot、用 OpenAI 登录走 ChatGPT Plus/Pro，以及通过 Models.dev 接 75 个以上提供商和本地模型。终端、桌面和 IDE 扩展是三种门。"),
    shot("opencode", "OpenCode 中文首页", "首页把免费模型和自备模型放在同一句里，并列出 Copilot 与 ChatGPT 登录。"),
    p("它没有自己的 Pro / Ultra 双池。你若登录 ChatGPT，用量在 OpenAI 那一侧；你若填写 DeepSeek 的基址，用量在 DeepSeek 的余额。官网还写它不保存代码和上下文，但请求仍会到达你选的模型。Zen 是他们挑选过的一份模型清单，用来减少你自己试提供方的时间，不是无限额度。"),
    links([{ href: "https://opencode.ai/zh", label: "OpenCode" }]),
  ],
  freebuff: [
    h2("广告换来的模型，和你可以挂上的既有代理"),
    p("Freebuff 首页写着由广告支持的编码模型，入口是 Desktop、CLI、Web、Cloud、Chat。它用一张图把自己标成 $0/年，旁边对比 OpenCode、Codex、Cursor、Claude Code、Devin 的标价。那些对比数字是它的营销图，不是那些产品的完整账单，尤其 Cursor 和 Claude Code 的真实花费还取决于模型池。"),
    shot("freebuff", "Freebuff 首页", "五种产品入口，以及它自己绘制的年费对比。使用前仍要读数据条款。"),
    p("赠送目录里的模型名字会变。桌面端还可以挂上你已经登录的 Claude Code 或 Codex，那部分用量回到原来的订阅。提示词可能参与广告分析，未公开的原理图和私有仓库不要进 Cloud 那一形态。"),
    links([{ href: "https://freebuff.com/", label: "Freebuff" }]),
  ],
  "local-models": [
    h2("本机没有官方价目表，有显存和能力两本账"),
    p("Ollama 一类运行时把权重放在你的机器上，并常常露出一个兼容接口。OpenCode 可以把提供方指到这个接口。没有按百万 token 的外部单价，有显存、速度，以及小模型在时序数字上更容易编造。程序可以免费，权重的许可证要单独看，有的权重允许商用，有的不行。"),
    p("工作模式就是：本地推理进程，加上一个认基址的代理。没有 Fast 档和 Credits 倍率。对不上云上代码模型时，把可以公开的手册页交给外部 Provider，私有录波留在本地。"),
    links([{ href: "https://opencode.ai/zh", label: "能接本地模型的客户端" }]),
  ],
  "grok-bot": [
    h2("角色菜单，共享的一台云电脑"),
    p("Grok Bot 按角色建多个 Bot，可以有例行任务。公开架构说明里，同一用户的 Bot 共享一台云电脑，所以模型都来自 Grok 这一侧，隔离粒度是用户不是 Bot。它出现在 Cursor 文档侧栏里，和编辑器里的 Agent 不是同一个菜单。用量挂在对应的 Grok 或 Cursor 方案上，具体包含关系以那一页的「包含 Cloud Agents / Grok」说明为准。"),
    p("适合值守和整理公开材料。不适合当作改死区的唯一差异视图。再开一个 Bot 不会得到新的安全边界。"),
    links([{ href: "https://cursor.com/docs/models-and-pricing", label: "Cursor 文档中的 Grok 条目" }]),
  ],
  muse: [
    h2("一个管家，一台虚拟机"),
    p("Muse 的公开材料把它写成一个人一台安全虚拟机上的长期管家，出站经过单独审批。模型是 Meta 这一侧的。Cursor 的价格表里另有一个叫 Muse Spark 的模型条目，那是编辑器里的第三方模型，不要和这个管家产品当成同一个开关。可用地区在公开材料里偏美国和加拿大，其他地方以官网为准。"),
    p("工作模式是云上的浏览器和存储，加上出站前的批准。没有「改本地仓库」的模式，除非你把文件拷来拷去。配额未在这篇里写死。"),
    links([{ href: "https://cursor.com/docs/models-and-pricing", label: "不要和 Muse Spark 价目混淆" }]),
  ],
  manus: [
    h2("任务模式和云电脑"),
    p("Manus 是任务型云端代理：拆目标、在远程环境里执行、把需要久留的项目放在云电脑上。模型不一定开放成可自带的 id。桌面端是观看窗口。Cue 是后来的个人代理应用，不要在任务菜单里找每个代理的电话和钱包。"),
    p("适合打开公开器件页并摘笔记。用量和邀请以 Manus 自己的方案页为准。登录后的规格书要不要交给云浏览器，是数据决定，不是模型决定。"),
    links([{ href: "/tools/browser-use", label: "它点网页时的机制" }]),
  ],
  cue: [
    h2("每个代理一套对外身份"),
    p("Cue 给个人代理单独的邮箱、电话、钱包和电脑。这是它的特色菜单，不是 Manus 任务视图的皮肤。模型没有作为可填写的 Provider 公开，因此搭配表里不给它连到 DeepSeek 的虚线。邀请制和未公开的配额保持未知，不写成 0 或无限。"),
    p("适合需要对外联系方式和支付上限的事。固件仓库默认不放进这只云电脑。"),
    links([{ href: "/tools/manus", label: "任务型云电脑是上一章" }]),
  ],
  yuanbao: [
    h2("办公交付菜单"),
    p("腾讯元宝公开说法是把任务交成幻灯片、文档、表格和网页。模型是腾讯一侧的对话模型，不是 WorkBuddy 的编程目录，也不是腾讯云上转售的那张 API 价目表。是否收费以产品内说明为准。若你看到它在浏览器里点击页面，那是 Browser Use，不是 IDE 的 Agent 模式。"),
    p("适合可以公开的测试数据。源码和未公开波形不要当成附件。"),
    links([{ href: "/tools/workbuddy", label: "编程去 WorkBuddy" }]),
  ],
  "computer-use": [
    h2("这是一种模式，不是一个模型池"),
    p("Computer Use 的循环是截图、决定指针或键盘、再截图。它没有自己的价目表。账单记在驱动这只手的那个 Agent 的模型上：Claude 的计算机使用、云端代理的桌面，或你本机客户端若提供了这项。换 DeepSeek 不会自动获得这只手。"),
    ul([
      "有 MCP 或命令行时，不要用像素去点菜单。",
      "只有 EDA、下载器、示波器软件时，才升到这一模式。",
      "最后一次写入设备前停给人确认。",
    ]),
    p("失败模式是点错、分辨率变化和弹窗。不写绕过登录或验证码的步骤。"),
    links([{ href: "/learn/tools-permissions", label: "和普通工具的权限差别" }]),
  ],
  "browser-use": [
    h2("三种菜单，一种循环"),
    p("浏览器 MCP、独立的 browser-use 运行时、云端代理自带的浏览器，菜单不同，循环相同：导航、点击、填表、读页面。模型仍是宿主那个 Agent 的模型。Cookie 和下载落在驱动浏览器的那台电脑上，可能是笔记本，也可能是云电脑。"),
    p("适合核对公开手册页上的封装。遇到登录就停。页面若有可下载的表格，用下载，不用点击来模拟接口。"),
    links([{ href: "/tools/computer-use", label: "桌面软件再升一级" }]),
  ],
  firmware: [
    h2("编程代理的模式，加上仪器"),
    p("这一章没有新的模型品牌。读手册可以用长上下文模型，改源码可以用代码模型，两者按搭配章切换。特色菜单是仓库说明、差异和已有的检查命令。仿真器和下载器不在模型菜单里。"),
    p("用量就是你选的那个代理的池。把电流单位写进仓库说明，能减少压缩之后重新发明单位的那部分浪费。"),
    links([{ href: "/learn/alignment", label: "续写不是测量" }]),
  ],
  pcb: [
    h2("三种工具，三种菜单"),
    p("KiCad 没有官方的大模型按钮。它的菜单是原理图、PCB 和脚本；代理通过脚本或社区 MCP 去跑检查、改网名、出料单，模型是你的编程代理。Flux 是浏览器里的另一套菜单：原理图、布局、协作，AI 功能写在它自己的产品里，账单在 Flux。Quilter 吃已有原理图，产出带物理检查的布局候选，账单在 Quilter。三套模型池互不继承。"),
    shot("flux", "Flux 产品页", "浏览器里的电路板环境。它的助手不是 KiCad 的一个插件名。"),
    p("功率级、栅极驱动和敏感模拟仍要人审。不能离开本机的设计，留在 KiCad 和本地脚本，不要为了使用 Flux 的菜单把原理图上传。"),
    links([
      { href: "https://www.flux.ai/", label: "Flux" },
      { href: "https://www.quilter.ai/", label: "Quilter" },
    ]),
  ],
  cad: [
    h2("装配菜单和生成草案"),
    p("Fusion 一类工具的菜单是实体、电路板外形和装配。生成式外形是草案命令，不是装配约束本身。CAD 里的助手用该产品自己的模型。仓库里写尺寸的代理用你的编程模型。两边通过导出的板框交换。"),
    p("用量在 CAD 订阅里。上传装配等于设计离开本机。安装孔、散热和连接器方向不要交给生成命令单独决定。"),
    links([{ href: "/tools/pcb", label: "板框从上一章来" }]),
  ],
  debug: [
    h2("仪器没有模型菜单"),
    p("示波器、逻辑分析仪和下载器的菜单是时基、触发和通道。模型只读你写成文字的记录。长日志可以换长上下文模型，改固件的那一步可以换代码模型。Computer Use 只有在必须操作仪器软件、又没有导出时才出现，并且停在确认前。"),
    p("没有单独的调试用量池。浪费来自把没有单位的照片反复送进长上下文。先把探头位置和单位写进记录，再谈换模型。"),
    links([{ href: "/learn/kv-cache", label: "长记录为什么贵" }]),
  ],
};
